### ISSUE TITLE
Doesn't work with nodejs 7.4.0

### ISSUE THREAD

**Issue by rod-stuchi** [markserv/markserv#11]
**node --version**
`v7.4.0`

**markserv**

```/home/rods/.asdf/installs/nodejs/7.4.0/.npm/lib/node_modules/markserv/node_modules/websocket.io/lib/socket.js:49
Socket.prototype.__proto__ = EventEmitter.prototype;
                                         ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/home/rods/.asdf/installs/nodejs/7.4.0/.npm/lib/node_modules/markserv/node_modules/websocket.io/lib/socket.js:49:42)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/rods/.asdf/installs/nodejs/7.4.0/.npm/lib/node_modules/markserv/node_modules/websocket.io/lib/protocols/drafts.js:12:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

```

With node 6.9.x works fine.

**Comment by F1LT3R** [comment]
Thanks, looking into it.

**Comment by F1LT3R** [comment]
The issue also exists in `servlr`: https://github.com/kavanagh/srvlr/issues/1
It's a known problem in `websocket.io`: https://github.com/LearnBoost/websocket.io/issues/55
And in `robohydra` https://github.com/robohydra/robohydra/issues/24

**Comment by F1LT3R** [comment]
Fixing this here: https://github.com/F1LT3R/markserv-legacy/pull/1

(This repo is being phased out of action and moved to `markserv-legacy` in prep for new version of markserv.

**Comment by F1LT3R** [comment]
Fixed

**Comment by F1LT3R** [comment]
@rod-stuchi can you try `npm install markserv -g` and let me know if this works for you now?

Thanks!

**Comment by rod-stuchi** [comment]
Thank you, I've notice that the problem was in one dependencies.

Great work, **markserv** is awesome!!

**Comment by rahul202** [comment]
Hi @rod-stuchi  what is the solution?  i tried @F1LT3R solution, but it dint work.. Can you please help me out over here.

**Comment by rahul202** [comment]
Which module had problem?

**Comment by rod-stuchi** [comment]
@rahul202  do you try to upgrade your version of markserv?
