### ISSUE TITLE
Error after upgrading

### ISSUE THREAD

**Issue by jeremiahfranz** [markserv/markserv#90]
Hello,

Previously running version 0.1.1 (!) on a fully updated CentOS 7.6 box. Upgraded to version 1.17.2 via npm.

Now the following output is generated when running the markserv binary:

---snip---
[root@pasta ~]# markserv
/usr/lib/node_modules/markserv/lib/server.js:578
const logActiveServerInfo = async (serveURL, httpPort, liveReloadPort, flags) => {
                                                       ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/markserv/lib/cli.js:9:18)
---snip---

Any help is greatly appreciated!

j

**Comment by F1LT3R** [comment]
I have just updated all dependencies to latest. Can you try with version `1.17.4` and let me know what you see?

Thanks for reporting this @jeremiahfranz !

**Comment by F1LT3R** [comment]
I assume it worked? Let me know if you're still having issues with v 1.19.1
